apiVersion : apps/v1
kind: Deployment
metadata:
  name: nbudhwaniwebgoat 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbudhwaniwebgoat
  template:
    metadata:
      labels:
        app: nbudhwaniwebgoat 
    spec:
      containers:
        - name: nbudhwaniwebgoat 
          image: webgoatcontainerregistry.azurecr.io/nbudhwaniwebgoat
          ports:
          - containerPort: 8080